import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header>
        <Link href={'/'}>MSSBLOG={`>`}NEXT</Link>
      </header>
      <main>{children}</main>
      <footer>
        <Link href={'/'}>&lt;&lt;&lt; BACK to INDEX</Link>
      </footer>
    </>
  )
}
